# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'SquaredUp V1' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for SquaredUp V1
  pod 'BraintreeDropIn'
  pod 'Braintree/PayPal'
  pod 'Braintree/Venmo'
  pod 'Braintree/Apple-Pay'

  target 'SquaredUp V1Tests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'SquaredUp V1UITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
